/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Hp' at '9/10/20 12:04 PM' with Gradle 3.0
 *
 * @author Hp, @date 9/10/20 12:04 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
